# workflow name
name: Deploy to Amazon EC2 / Spring Boot with Maven

# env variables
env:
  PROJECT_NAME: money-cracker-backend
  BUCKET_NAME: mc-github-actions-be
  CODE_DEPLOY_APP: MC-BE-deploy
  CODE_DEPLOY_DEPLOYMENT_GROUP: MC-BE-deploy-group

# trigger
on:
  push:
    branches: [ main ]

jobs:
  build:
    name: CI/CD
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      # Caching dependencies
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION}}

      - name: Get secrets from AWS Secrets Manager
        run: |
          AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
          aws secretsmanager get-secret-value --region ${{ secrets.AWS_REGION }} --secret-id prod/env.properties | \
          jq -r ".SecretString" >> src/main/resources/prod-env.properties

      - name: Get Github action IP
        id: ip
        uses: haythem/public-ip@v1.3.0

      - name: Add IP to EC2 security group
        run: |
          aws ec2 authorize-security-group-ingress --group-id ${{ secrets.EC2_SECURITY_GROUP_ID }} \
          --protocol tcp --port 8080 --cidr ${{ steps.ip.outputs.ipv4 }}/32

      - name: Add IP to RDS security group
        run: |
          aws ec2 authorize-security-group-ingress --group-id ${{ secrets.RDS_SECURITY_GROUP_ID }} \
          --protocol tcp --port 3306 --cidr ${{ steps.ip.outputs.ipv4 }}/32

      - name: Build with Maven
        run: mvn -B package --file pom.xml -Dspring-boot.run.arguments=--spring.config.location=file:src/main/resources/prod-env.properties

      - name: Make zip file
        run: zip -r ./$PROJECT_NAME.zip .
        shell: bash

      # Upload to S3 storage
      - name: Upload to S3
        run: aws s3 cp $PROJECT_NAME.zip s3://$BUCKET_NAME/deploy/$PROJECT_NAME.zip --region ap-northeast-2

      # Deploy
      - name: Code Deploy
        run: |
          aws deploy create-deployment --application-name $CODE_DEPLOY_APP \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --deployment-group-name $CODE_DEPLOY_DEPLOYMENT_GROUP \
          --s3-location bucket=$BUCKET_NAME,bundleType=zip,key=deploy/$PROJECT_NAME.zip